### ISSUE TITLE
What is a good footnote-enhancing WordPress plugin?

### ISSUE THREAD

**Issue by waldoj** [electionlaw/eBenchbook#3]
Something that will make it easier to embed footnotes and render them as nice pop-ups, in the style of Marco.org, Kottke.org, or Daringfireball.net.

**Comment by waldoj** [comment]
[Civil Footnotes](https://wordpress.org/plugins/civil-footnotes/) looks like it'll do the trick.

I'm not thrilled with the formatting, which is to insert all footnotes in double quotes, e.g.,:

> No individual shall be limited in contributions((Lack of contribution limits for elected officials could lead to appearance of corruption/quid pro quo arrangements between individuals or corporations and such officials.)), not withstanding federal regulation.

That would result in:

> No individual shall be limited in contributions<sup>1</sup>, not withstanding federal regulation.

Passing the mouse over <sup>1</sup> would display a bubble with the contents of "((...))."

**Comment by waldoj** [comment]
It looks like WordPress just has no native footnoting functionality to hook into. _Anything_ is a hack. Its formatting bar doesn't even include superscripting text.

**Comment by waldoj** [comment]
Eh, Civil Footnotes is _OK._ It embeds the text within the `title` attribute, which is inadequate for our purposes. It's pretty trivial to hook into this with a bit of jQuery, to display the text more nicely, but I'd rather solve this with one of WordPress's existing plugins.

**Comment by waldoj** [comment]
Tried out [Simple Footnotes](https://wordpress.org/plugins/simple-footnotes/). Too simple.

**Comment by waldoj** [comment]
Tried out [Easy Footnotes](https://wordpress.org/plugins/easy-footnotes/). We have a winner.

**Comment by waldoj** [comment]
@rgreenwm, [here's an example of footnotes](http://ebenchbook.jaquith.org/recounts/defeated-candidate/). In the body of the law text, look for <sup>1</sup>, etc., and pass your mouse over them.

**Comment by rgreenwm** [comment]
I think that’s great—especially for shorter commentary. Once it gets long, it might be difficult because you’re holding your mouse over it while you might need to be scrolling down? Perhaps there could be a different protocol for longer commentary? Or maybe we just will need to get pithy.

**Comment by waldoj** [comment]
Space constraints are inherent to the footnote-bubble interface. We can get around that by a) just using actual footnotes at the bottom of the page, b) providing analysis with a per-law granularity instead of something finer, or c) using a totally different interface.

Or, alternately, you could accept those space constraints, regard inline notes as inherently brief, and put more in-depth analysis within the primary body of textual analysis.
